staging:
  aws_access_key: 1HNRH1HNMENG1BTNVTG2
  aws_secret_access_key: 
  bucket_base_name: focon

production:
  aws_access_key: 1HNRH1HNMENG1BTNVTG2
  aws_secret_access_key: 
  bucket_base_name: focon