staging:
  aws_access_key: 1HNRH1HNMENG1BTNVTG2
  aws_secret_access_key: ryKEDjZK25xEnqOdumpYp7AQN2l8OuOYXfrULlvu
  bucket_base_name: focon

production:
  aws_access_key: 1HNRH1HNMENG1BTNVTG2
  aws_secret_access_key: ryKEDjZK25xEnqOdumpYp7AQN2l8OuOYXfrULlvu
  bucket_base_name: focon